In [1]:
import pandas as pd
from datetime import datetime, date
import toolbox
import os

In [2]:
date.today()

datetime.date(2022, 4, 25)

In [3]:
datetime.now()

datetime.datetime(2022, 4, 25, 16, 15, 12, 12277)

In [13]:
# Control Panel for Kernels
bio_ON = False
Test_run = True

# Reading arguments


diffusion = True
sinking_v = True
fragmentation = True
frag_timescale = 100
frag_mode = 1/2
sim_time = 30
# Initial condition
initial_depth = 5179
submission_date = datetime.now()
particle_radius = 5e-5
particle_density = 1380
lon_sample = 6.287
lat_sample = -32.171
start_time = datetime.strptime('2019-12-30 12:00:00', '%Y-%m-%d %H:%M:%S')
ID = toolbox.generate_unique_key()

In [14]:
def log_params():
    log = {'ID': [ID],
       'test_run': [Test_run],
       'date': [submission_date],
       'depth': [initial_depth],
       'lon': [lon_sample],
       'lat': [lat_sample],
       'start_time': [start_time],
       'sim_time': [sim_time],
       'radius': [particle_radius],
       'density': [particle_density],
       'diffusion': [diffusion],
       'sinking_vel': [sinking_v],
       'fragmentation': [fragmentation],
       'frag_timescale': [frag_timescale],
       'frag_mode': [frag_mode],
        'bio_fields': [bio_ON]}
    
    log = pd.DataFrame(log)
    
    return log

In [16]:
log_run = log_params()

In [17]:
log_run

,ID,test_run,date,depth,lon,lat,start_time,sim_time,radius,density,diffusion,sinking_vel,fragmentation,frag_timescale,frag_mode,bio_fields
0,DZL8VH,True,2022-04-25 16:56:31.327988,5179,6.287,-32.171,2019-12-30 12:00:00,30,0.00005,1380,True,True,True,100,0.5,False

In [19]:
log = pd.read_csv(log_file, index_col=0)

In [6]:
log_file = '../log_simulations.csv'

In [69]:
if os.path.exists(log_file):
    log = pd.read_csv(log_file, index_col=0)

In [70]:
log

,ID,date,depth,lon,lat,start_time,radius,density,diffusion,sinking_vel,fragmentation,frag_timescale,frag_mode,bio_fields
0,SBO7RC,2022-04-25 13:53:12.034260,5179,6.287,-32.171,2019-12-30 12:00:00.000000,0.00005,1380,True,True,True,100,0.5,False

In [71]:
pd.concat([log, log_run], axis=0)

,ID,date,depth,lon,lat,start_time,radius,density,diffusion,sinking_vel,fragmentation,frag_timescale,frag_mode,bio_fields,test_run
0,SBO7RC,2022-04-25 13:53:12.034260,5179,6.287,-32.171,2019-12-30 12:00:00.000000,0.00005,1380,True,True,True,100,0.5,False,NaN
0,A249XY,2022-04-25 14:36:22.295882,5179,6.287,-32.171,2019-12-30 12:00:00,0.00005,1380,True,True,True,100,0.5,False,True

In [21]:
pd.read_csv(log_file, index_col=0)

,ID,test_run,date,depth,lon,lat,start_time,radius,density,diffusion,sinking_vel,fragmentation,frag_timescale,frag_mode,bio_fields
0,ZYPREV,True,2022-04-25 15:36:56.912928,5179,6.287,-32.171,2019-12-30 12:00:00,0.00005,1380,False,True,True,10,0.5,False
0,A4MWNG,True,2022-04-25 15:37:09.451352,5179,6.287,-32.171,2019-12-30 12:00:00,0.00005,1380,False,True,True,100,0.5,False
0,4ZUA8B,True,2022-04-25 15:37:23.763885,5179,6.287,-32.171,2019-12-30 12:00:00,0.00005,1380,False,True,False,0,0.5,False
0,6I24FN,True,2022-04-25 16:34:32.943603,5179,6.287,-32.171,2019-12-30 12:00:00,0.00005,1380,False,True,True,1,0.5,False